// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// flutter pub add firebase_core
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcmuI9nKTIZN8XC3tkOLn83M3Svej7zlY',
    appId: '1:207712451184:web:861060d7744eaa802f52b5',
    messagingSenderId: '207712451184',
    projectId: 'chatapp-e6bf5',
    authDomain: 'chatapp-e6bf5.firebaseapp.com',
    storageBucket: 'chatapp-e6bf5.appspot.com',
    measurementId: 'G-WJJNV6XPCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ9JWGF0wdSbP0H9IIHtE0IM_DperR7tY',
    appId: '1:207712451184:android:918d0774f06a931f2f52b5',
    messagingSenderId: '207712451184',
    projectId: 'chatapp-e6bf5',
    storageBucket: 'chatapp-e6bf5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM4eCk7yK7fc-2G7SHOPaTWId1CN-DWhk',
    appId: '1:207712451184:ios:504a24bbf60ce7a22f52b5',
    messagingSenderId: '207712451184',
    projectId: 'chatapp-e6bf5',
    storageBucket: 'chatapp-e6bf5.appspot.com',
    iosClientId:
        '207712451184-slh3s532k0bh5qrvgdci2betu5ppoun5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM4eCk7yK7fc-2G7SHOPaTWId1CN-DWhk',
    appId: '1:207712451184:ios:504a24bbf60ce7a22f52b5',
    messagingSenderId: '207712451184',
    projectId: 'chatapp-e6bf5',
    storageBucket: 'chatapp-e6bf5.appspot.com',
    iosClientId:
        '207712451184-slh3s532k0bh5qrvgdci2betu5ppoun5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
